basePath: /api/v1
definitions:
  handler.GenericResponse:
    properties:
      data:
        description: omitempty agar tidak tampil jika nil
      message:
        type: string
      success:
        type: boolean
    type: object
  handler.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.LoginResponse:
    properties:
      accessToken:
        type: string
    type: object
  handler.ProfileData:
    properties:
      created_at:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      role:
        type: string
      username:
        type: string
    type: object
  handler.ProfileResponse:
    properties:
      data:
        $ref: '#/definitions/handler.ProfileData'
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is the API documentation for STMADB Portal Backend.
  title: STMADB Portal Backend API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token.
      parameters:
      - description: Login Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login Successful
          schema:
            allOf:
            - $ref: '#/definitions/handler.GenericResponse'
            - properties:
                data:
                  $ref: '#/definitions/handler.LoginResponse'
              type: object
        "400":
          description: Invalid Request
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.GenericResponse'
      summary: User login
      tags:
      - Authentication
  /auth/profile:
    get:
      description: Get the profile of the currently authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: Profile Retrieved
          schema:
            $ref: '#/definitions/handler.ProfileResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.GenericResponse'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - Authentication
  /health:
    get:
      consumes:
      - application/json
      description: get the status of server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server
      tags:
      - Health Check
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
